# .readthedocs.yml

version: 2
sphinx:
  # Path to Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

python:
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/environment-rtd.yml
